# Generated by Django 2.1.4 on 2019-01-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridaygame', '0001_=added models'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
